// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Op    string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Var   string                 `protobuf:"bytes,3,opt,name=var,proto3" json:"var,omitempty"`
	// Types that are valid to be assigned to LeftType:
	//
	//	*Instruction_LeftInt
	//	*Instruction_LeftVar
	LeftType isInstruction_LeftType `protobuf_oneof:"left_type"`
	// Types that are valid to be assigned to RightType:
	//
	//	*Instruction_RightInt
	//	*Instruction_RightVar
	RightType     isInstruction_RightType `protobuf_oneof:"right_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instruction) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Instruction) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *Instruction) GetLeftType() isInstruction_LeftType {
	if x != nil {
		return x.LeftType
	}
	return nil
}

func (x *Instruction) GetLeftInt() int64 {
	if x != nil {
		if x, ok := x.LeftType.(*Instruction_LeftInt); ok {
			return x.LeftInt
		}
	}
	return 0
}

func (x *Instruction) GetLeftVar() string {
	if x != nil {
		if x, ok := x.LeftType.(*Instruction_LeftVar); ok {
			return x.LeftVar
		}
	}
	return ""
}

func (x *Instruction) GetRightType() isInstruction_RightType {
	if x != nil {
		return x.RightType
	}
	return nil
}

func (x *Instruction) GetRightInt() int64 {
	if x != nil {
		if x, ok := x.RightType.(*Instruction_RightInt); ok {
			return x.RightInt
		}
	}
	return 0
}

func (x *Instruction) GetRightVar() string {
	if x != nil {
		if x, ok := x.RightType.(*Instruction_RightVar); ok {
			return x.RightVar
		}
	}
	return ""
}

type isInstruction_LeftType interface {
	isInstruction_LeftType()
}

type Instruction_LeftInt struct {
	LeftInt int64 `protobuf:"varint,4,opt,name=left_int,json=leftInt,proto3,oneof"`
}

type Instruction_LeftVar struct {
	LeftVar string `protobuf:"bytes,5,opt,name=left_var,json=leftVar,proto3,oneof"`
}

func (*Instruction_LeftInt) isInstruction_LeftType() {}

func (*Instruction_LeftVar) isInstruction_LeftType() {}

type isInstruction_RightType interface {
	isInstruction_RightType()
}

type Instruction_RightInt struct {
	RightInt int64 `protobuf:"varint,6,opt,name=right_int,json=rightInt,proto3,oneof"`
}

type Instruction_RightVar struct {
	RightVar string `protobuf:"bytes,7,opt,name=right_var,json=rightVar,proto3,oneof"`
}

func (*Instruction_RightInt) isInstruction_RightType() {}

func (*Instruction_RightVar) isInstruction_RightType() {}

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  []*Instruction         `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateRequest) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type ResultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Var           string                 `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultItem) Reset() {
	*x = ResultItem{}
	mi := &file_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultItem) ProtoMessage() {}

func (x *ResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultItem.ProtoReflect.Descriptor instead.
func (*ResultItem) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *ResultItem) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *ResultItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CalculateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResultItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateResponse) GetItems() []*ResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/calculator.proto\x12\n" +
	"calculator\"\xd6\x01\n" +
	"\vInstruction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03var\x18\x03 \x01(\tR\x03var\x12\x1b\n" +
	"\bleft_int\x18\x04 \x01(\x03H\x00R\aleftInt\x12\x1b\n" +
	"\bleft_var\x18\x05 \x01(\tH\x00R\aleftVar\x12\x1d\n" +
	"\tright_int\x18\x06 \x01(\x03H\x01R\brightInt\x12\x1d\n" +
	"\tright_var\x18\a \x01(\tH\x01R\brightVarB\v\n" +
	"\tleft_typeB\f\n" +
	"\n" +
	"right_type\"O\n" +
	"\x10CalculateRequest\x12;\n" +
	"\finstructions\x18\x01 \x03(\v2\x17.calculator.InstructionR\finstructions\"4\n" +
	"\n" +
	"ResultItem\x12\x10\n" +
	"\x03var\x18\x01 \x01(\tR\x03var\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"A\n" +
	"\x11CalculateResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.calculator.ResultItemR\x05items2]\n" +
	"\x11CalculatorService\x12H\n" +
	"\tCalculate\x12\x1c.calculator.CalculateRequest\x1a\x1d.calculator.CalculateResponseB\x0fZ\rcalculator/pbb\x06proto3"

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData []byte
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_calculator_proto_goTypes = []any{
	(*Instruction)(nil),       // 0: calculator.Instruction
	(*CalculateRequest)(nil),  // 1: calculator.CalculateRequest
	(*ResultItem)(nil),        // 2: calculator.ResultItem
	(*CalculateResponse)(nil), // 3: calculator.CalculateResponse
}
var file_proto_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculateRequest.instructions:type_name -> calculator.Instruction
	2, // 1: calculator.CalculateResponse.items:type_name -> calculator.ResultItem
	1, // 2: calculator.CalculatorService.Calculate:input_type -> calculator.CalculateRequest
	3, // 3: calculator.CalculatorService.Calculate:output_type -> calculator.CalculateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	file_proto_calculator_proto_msgTypes[0].OneofWrappers = []any{
		(*Instruction_LeftInt)(nil),
		(*Instruction_LeftVar)(nil),
		(*Instruction_RightInt)(nil),
		(*Instruction_RightVar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
