openapi: 3.0.0
info:
  title: Calculator API
  description: Сервис вычисления арифметических выражений с параллельной обработкой
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Локальный сервер

paths:
  /calculate:
    post:
      summary: Обработать список инструкций
      description: Принимает JSON-массив инструкций, возвращает результаты указанных переменных
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Instruction"
      responses:
        "200":
          description: Результаты вычисления
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "400":
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Instruction:
      type: object
      properties:
        type:
          type: string
          example: calc
          enum:
            - calc
            - print
        op:
          type: string
          example: "+"
          enum:
            - "+"
            - "-"
            - "*"
        var:
          type: string
          example: x
        left:
          oneOf:
            - type: integer
            - type: string
          example: 1
        right:
          oneOf:
            - type: integer
            - type: string
          example: 2
      required:
        - type
        - var
      required_when_type_calc:
        - op
        - left
        - right

    ResultItem:
      type: object
      properties:
        var:
          type: string
        value:
          type: integer
      required:
        - var
        - value

    Response:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ResultItem"
      required:
        - items
